name: turtles 
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - matplotlib=3.5.2
  - pip:
    - datasets==2.4.0
    - opencv-python==4.1.2.30
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - pytorch-pretrained-biggan==0.1.1
    - datasets==2.6.1
    - evaluate==0.3.0
